// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationLayeredArchitecture.Models;

#nullable disable

namespace WebApplicationLayeredArchitecture.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    partial class AppdbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("WebApplicationLayeredArchitecture.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("WebApplicationLayeredArchitecture.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("genreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("genreId");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("WebApplicationLayeredArchitecture.Models.Movie", b =>
                {
                    b.HasOne("WebApplicationLayeredArchitecture.Models.Genre", "genre")
                        .WithMany("movies")
                        .HasForeignKey("genreId");

                    b.Navigation("genre");
                });

            modelBuilder.Entity("WebApplicationLayeredArchitecture.Models.Genre", b =>
                {
                    b.Navigation("movies");
                });
#pragma warning restore 612, 618
        }
    }
}
